### CALCULAR DÍVIDA COMPLETA
POST http://localhost:3000/divida
Content-Type: application/json
Accept: application/json

{
  "valorOriginal": 1000,
  "taxaMulta": 50,
  "periodoMeses": 10,
  "taxaJurosMensal": 5
}

### EXEMPLO DE RESPOSTA ESPERADA (apenas para referência)
#{
#  "valorOriginal": 1000,
#  "multa": 500,
#  "juros": "628.89",
#  "valorFinal": 2128.89
#}